#file: noinspection undefined
spring:
  application:
    name: rental-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
  jpa:
    generate-ddl: false
    open-in-view: false
server:
  tomcat:
    max-part-count: 20
  port: 8080

custom:
  map:
    title_image_key: "title"
    images_key: "images"
  pagination:
    size: 5
  buckets:
    car-image: cars
    make-image: makes

minio:
  url:
    time-to-live: 7