#file: noinspection undefined
spring:
  application:
    name: rental-service-dev
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: car-rental-app
            client-secret: kvTfHzdUWRInkgRNmN6Ruixl2KuBhB8E
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/rental-service-realm
            user-name-attribute: preferred_username
  datasource:
    url: jdbc:postgresql://localhost:5432/developer
    username: developer
    password: developer
  jpa:
    show-sql: true
  liquibase:
    url: jdbc:postgresql://localhost:5432/developer
    user: developer
    password: developer
    change-log: db/changelog/db.changelog-master.yml
  devtools:
    add-properties: true
minio:
  access-key: developer
  secret-key: developer
  endpoint: http://localhost:9000
  endpoint-override: http://localhost:9000
  default-bucket: developer

logging:
  level:
    org:
      springframework:
        security: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    org.apache.coyote.http11: DEBUG
    org.springframework.web.multipart.support.StandardMultipartHttpServletRequest: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter: TRACE
    org.springframework.http.converter: TRACE
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: TRACE
    org.springframework.web.servlet.mvc.method.annotation.ServletModelAttributeMethodProcessor: TRACE