#file: noinspection undefined
spring:
  application:
    name: rental-service-prod
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
  jpa:
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_REDIRECT_URI}
            scope: openid
        provider:
          keycloak:
#            authorization-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_AUTH_URI}
#            token-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_TOKEN_URI}
#            user-info-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_USER_INFO_URI}
#            jwk-set-uri:  ${SPRING_SECURITY_OAUTH2_PROVIDER_JWKS_URI}
            issuer-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_ISSUER_URI}
            user-name-attribute: preferred_username
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

minio:
  access-key: ${SPRING_MINIO_USERNAME}
  secret-key: ${SPRING_MINIO_PASSWORD}
  endpoint: ${SPRING_MINIO_ENDPOINT}
  endpoint-override: ${SPRING_MINIO_ENDPOINT_OVERRIDE}
  default-bucket: ${SPRING_MINIO_DEFAULT_BUCKET}