#file: noinspection undefined
spring:
  application:
    name: rental-service-prod
  liquibase:
    change-log: db/changelog/db.changelog-master.yml


minio:
  access-key: ${SPRING_MINIO_USERNAME}
  secret-key: ${SPRING_MINIO_PASSWORD}
  endpoint: ${SPRING_MINIO_ENDPOINT}
  endpoint-override: ${SPRING_MINIO_ENDPOINT_OVERRIDE}
  default-bucket: ${SPRING_MINIO_DEFAULT_BUCKET}