spring:
  application:
    name: Rental Service

  liquibase:
    change-log: db/changelog/db.changelog-master.yml
    liquibase-schema: liquibase
    default-schema: ${custom.datasource.schema}

  datasource:
    url: jdbc:postgresql://localhost:5432/rentalservice2?currentSchema=${custom.datasource.schema}
    username: postgres
    password: 123456778
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    open-in-view: false

custom:
  pagination:
    size: 5

  buckets:
    car-image: cars
    make-image: makes
  rest-clients:
    fileStore: http://localhost:8081/api
  datasource:
    schema: common

logging:
  level:
    org:
      springframework:
        security: DEBUG
