name: dev-fs
services:
  postgres:
    image: postgres:17-alpine
    env_file:
      - dev.env
    ports:
      - "5433:5432"
  minio:
    image: quay.io/minio/minio:latest
    env_file:
      - dev.env
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'