spring:
  application:
    name: rental-service-dev
  docker:
    compose:
      enabled: true
      file: ./app/docker-compose.yml
  jpa:
    show-sql: true
  devtools:
    add-properties: true
  liquibase:
    change-log: db/changelog/db.changelog-master-dev.yml

logging:
  level:
    org:
      springframework:
        security: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    org.apache.coyote.http11: DEBUG
    org.springframework.web.multipart.support.StandardMultipartHttpServletRequest: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter: TRACE
    org.springframework.http.converter: TRACE
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: TRACE
    org.springframework.web.servlet.mvc.method.annotation.ServletModelAttributeMethodProcessor: TRACE