#file: noinspection undefined
spring:
  application:
    name: rental-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB


#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8082/realms/rental-service
#            user-name-attribute: preferred_username
#        registration:
#          keycloak:
#            client-id: rental-service
#            client-secret: nZ0a6jitcMk7qplLofkZaDGHxyG2PAxF
#            scope: openid
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8082/realms/rental-service

  jpa:
    generate-ddl: false
    open-in-view: false
server:
  tomcat:
    max-part-count: 15
  port: 8080

custom:
  map:
    title_image_key: "title"
    images_key: "images"
  pagination:
    size: 5
  buckets:
    car-image: cars
    make-image: makes
  rest-clients:
    fileStore: http://localhost:8081/api/files

logging:
  level:
    org:
      springframework:
        security: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE


