spring:
  application:
    name: rental-service
  profiles:
    active: dev
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8082/realms/rental-service
#            user-name-attribute: preferred_username
#        registration:
#          keycloak:
#            client-id: rental-service
#            client-secret: nZ0a6jitcMk7qplLofkZaDGHxyG2PAxF
#            scope: openid
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8082/realms/rental-service

  jpa:
    generate-ddl: false
    open-in-view: false
server:
  port: 8080
custom:
  pagination:
    size: 5
  buckets:
    car-image: cars
    make-image: makes
  rest-clients:
    fileStore: http://localhost:8081/api/files

logging:
  level:
    org:
      springframework:
        security: DEBUG

