#file: noinspection undefined
spring:
  application:
    name: rs-file-service-dev
  docker:
    compose:
      enabled: true
      file: ./file-service/docker-compose.yml

minio:
  access-key: minioadmin
  secret-key: minioadmin
  endpoint: http://localhost:9000
  endpoint-override: http://localhost:9000
  default-bucket: minioadmin

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter: TRACE
    org.springframework.web.servlet.mvc.method.annotation.ServletModelAttributeMethodProcessor: TRACE
    org.springframework.web.method.annotation.ModelAttributeMethodProcessor: TRACE
    org.springframework.http.converter: TRACE
    org.springframework.web.multipart: TRACE
