#file: noinspection undefined
spring:
  application:
    name: file-service
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8081


minio:
  url:
    time-to-live: 7