spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
#    security:
#      oauth2:
#        resourceserver:
#          jwt:
#            jwk-set-uri: http://ums-service:8081/api/token/jwks
    jpa:
      open-in-view: false

minio:
  access-key: ${SPRING_MINIO_USERNAME}
  secret-key: ${SPRING_MINIO_PASSWORD}
  endpoint: ${SPRING_MINIO_ENDPOINT}
  endpoint-override: ${SPRING_MINIO_ENDPOINT_OVERRIDE}
  default-bucket: ${SPRING_MINIO_DEFAULT_BUCKET}